# Generated by Django 2.2.6 on 2019-10-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.IntegerField(unique=True)),
                ('region_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Region',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('population', models.FloatField()),
                ('average_age', models.FloatField()),
                ('distr_code', models.IntegerField()),
                ('dept_code', models.IntegerField()),
                ('region', models.ForeignKey(db_column='region_code', on_delete=django.db.models.deletion.CASCADE, related_name='city_region', to='cities.Region', to_field='region_code')),
            ],
            options={
                'verbose_name': 'Town',
            },
        ),
    ]
